# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa1dc0797557a3dd443224a828a462c3779003ab24b5fbc7063cbb3c2efb0fe4f1d4625dbc6fed6596682bd6efe1aaad8e46b253fbbb374c931057acc73b48a0

test:
  secret_key_base: f7d0cad0bddc0a1eb8d045cc82fd5e7b168b0f86aff49b4322258c2387f57aeed488d0813571d986262b0405336eac4cd540f28285150e12a79cbdf4be7ebcad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
